name: Node.js CI - Practica React Native

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v4

    - name: Configurar Node.js v22
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Instalar dependencias
      run: npm install

    - name: Validacion del proyecto
      run: echo "¡El flujo de CI se ejecuto e instalo correctamente!"